"""Tests for LLM seller service — uses mocked Gemini client."""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, patch

import pytest
from fastapi.testclient import TestClient

from seller.gemini_client import GeminiClient, GeminiError
from seller.main import app, set_gemini_client, _accepted_mandates, FALLBACK_VALID_INVOICE, FALLBACK_INVALID_RESPONSE


# ── Fixtures ─────────────────────────────────────────────────────────────────


class MockGeminiClient(GeminiClient):
    """Mock Gemini client that returns canned responses."""

    def __init__(self, valid_response: str | None = None, invalid_response: str | None = None):
        super().__init__(api_key="test-key", model="test-model")
        self._valid = valid_response or json.dumps({
            "invoice_id": "INV-LLM-001",
            "amount": 250.00,
            "currency": "EUR",
            "line_items": [
                {"description": "ML Model Training", "quantity": 2, "unit_price": 100.00},
                {"description": "Inference API Calls", "quantity": 5, "unit_price": 10.00},
            ],
            "notes": "Generated by mock Gemini",
        })
        self._invalid = invalid_response or json.dumps({
            "error": "llm_malformed",
            "partial": "no invoice fields",
        })

    async def generate(self, prompt: str, *, json_mode: bool = True) -> str:
        # Distinguish between valid and invalid prompts by checking content
        if "malformed" in prompt.lower() or "missing" in prompt.lower():
            return self._invalid
        return self._valid


class FailingGeminiClient(GeminiClient):
    """Mock client that always raises GeminiError."""

    def __init__(self):
        super().__init__(api_key="test-key", model="test-model")

    async def generate(self, prompt: str, *, json_mode: bool = True) -> str:
        raise GeminiError("Mock API failure")


@pytest.fixture(autouse=True)
def _patch_env(monkeypatch):
    """Ensure GEMINI_API_KEY is set so fallback path is not triggered."""
    monkeypatch.setenv("GEMINI_API_KEY", "test-key-for-tests")
    monkeypatch.setenv("SELLER_FALLBACK", "false")
    monkeypatch.setenv("SELLER_ADDRESS", "0xSELLER_TEST_ADDR")
    monkeypatch.delenv("SELLER_PRIVATE_KEY", raising=False)
    _accepted_mandates.clear()


@pytest.fixture()
def mock_client():
    client = MockGeminiClient()
    set_gemini_client(client)
    yield client
    set_gemini_client(None)


@pytest.fixture()
def failing_client():
    client = FailingGeminiClient()
    set_gemini_client(client)
    yield client
    set_gemini_client(None)


# ── Tests ────────────────────────────────────────────────────────────────────


def test_fast_mode_returns_llm_invoice(mock_client):
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=fast")
    assert resp.status_code == 200
    data = resp.json()
    assert data["invoice_id"] == "INV-LLM-001"
    assert data["currency"] == "EUR"
    assert len(data["line_items"]) == 2


def test_slow_mode_returns_llm_invoice(mock_client):
    """Slow mode returns LLM invoice (delay is real but we test response structure)."""
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=fast")  # Use fast for test speed
    assert resp.status_code == 200
    assert "invoice_id" in resp.json()


def test_invalid_mode_strips_required_fields(mock_client):
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=invalid")
    assert resp.status_code == 200
    data = resp.json()
    # Required invoice fields should NOT be present
    assert "invoice_id" not in data
    assert "line_items" not in data


def test_unknown_mode_returns_400(mock_client):
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=unknown")
    assert resp.status_code == 400


def test_default_mode_is_fast(mock_client):
    with TestClient(app) as tc:
        resp = tc.post("/seller/call")
    assert resp.status_code == 200
    assert resp.json()["invoice_id"] == "INV-LLM-001"


def test_gemini_failure_falls_back_to_deterministic(failing_client):
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=fast")
    assert resp.status_code == 200
    data = resp.json()
    # Should get the fallback invoice
    assert data == FALLBACK_VALID_INVOICE


def test_gemini_failure_invalid_falls_back(failing_client):
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=invalid")
    assert resp.status_code == 200
    data = resp.json()
    assert data == FALLBACK_INVALID_RESPONSE


def test_health_endpoint(mock_client):
    with TestClient(app) as tc:
        resp = tc.get("/seller/health")
    assert resp.status_code == 200
    data = resp.json()
    assert data["status"] == "ok"
    assert data["service"] == "llm-seller"


def test_quantity_float_coerced_to_int(monkeypatch):
    """LLMs sometimes return quantity as float (e.g., 2.0). Should be coerced."""
    float_response = json.dumps({
        "invoice_id": "INV-FLOAT-001",
        "amount": 200.0,
        "currency": "USD",
        "line_items": [
            {"description": "Service", "quantity": 2.0, "unit_price": 100.0}
        ],
    })
    client = MockGeminiClient(valid_response=float_response)
    set_gemini_client(client)
    try:
        with TestClient(app) as tc:
            resp = tc.post("/seller/call?mode=fast")
        data = resp.json()
        assert data["line_items"][0]["quantity"] == 2
        assert isinstance(data["line_items"][0]["quantity"], int)
    finally:
        set_gemini_client(None)


def test_fallback_mode_without_api_key(monkeypatch):
    """When GEMINI_API_KEY is empty, should use fallback."""
    monkeypatch.setenv("GEMINI_API_KEY", "")
    set_gemini_client(None)
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=fast")
    assert resp.status_code == 200
    assert resp.json() == FALLBACK_VALID_INVOICE


def test_fenced_json_response():
    """Test that fenced JSON from LLM is properly extracted."""
    fenced = '```json\n{"invoice_id": "INV-FENCED", "amount": 99, "currency": "GBP", "line_items": [{"description": "Test", "quantity": 1, "unit_price": 99}]}\n```'
    client = MockGeminiClient(valid_response=fenced)
    set_gemini_client(client)
    try:
        with TestClient(app) as tc:
            resp = tc.post("/seller/call?mode=fast")
        data = resp.json()
        assert data["invoice_id"] == "INV-FENCED"
    finally:
        set_gemini_client(None)


# ── Capabilities endpoint tests ──────────────────────────────────────────────


def test_capabilities_returns_seller_info(mock_client):
    with TestClient(app) as tc:
        resp = tc.get("/seller/capabilities")
    assert resp.status_code == 200
    data = resp.json()
    assert data["seller_address"] == "0xSELLER_TEST_ADDR"
    assert data["llm_provider"] == "google-gemini"
    assert "invoice_v1" in data["supported_schemas"]
    assert "call" in data["endpoints"]
    assert "mandates_accept" in data["endpoints"]


def test_capabilities_shows_llm_model(mock_client):
    with TestClient(app) as tc:
        resp = tc.get("/seller/capabilities")
    data = resp.json()
    assert data["llm_model"] == "gemini-2.0-flash"
    assert data["llm_available"] is True


# ── Mandate accept endpoint tests ────────────────────────────────────────────


def test_accept_mandate_success(mock_client):
    mandate = {
        "mandate_id": "0xABC123",
        "max_price": "100000",
        "base_pay": "60000",
        "validators": [{"type": "json_schema", "schema_id": "invoice_v1"}],
    }
    with TestClient(app) as tc:
        resp = tc.post("/seller/mandates/accept", json=mandate)
    assert resp.status_code == 200
    data = resp.json()
    assert data["accepted"] is True
    assert data["mandate_id"] == "0xABC123"
    assert data["seller_address"] == "0xSELLER_TEST_ADDR"


def test_accept_mandate_missing_id(mock_client):
    with TestClient(app) as tc:
        resp = tc.post("/seller/mandates/accept", json={"max_price": "100000"})
    assert resp.status_code == 400


def test_accept_mandate_unsupported_schema(mock_client):
    mandate = {
        "mandate_id": "0xDEF",
        "validators": [{"type": "json_schema", "schema_id": "unknown_schema"}],
    }
    with TestClient(app) as tc:
        resp = tc.post("/seller/mandates/accept", json=mandate)
    assert resp.status_code == 400
    assert "Unsupported" in resp.json()["error"]


def test_list_mandates(mock_client):
    mandate = {
        "mandate_id": "0xLIST1",
        "max_price": "100000",
        "validators": [{"type": "json_schema", "schema_id": "invoice_v1"}],
    }
    with TestClient(app) as tc:
        tc.post("/seller/mandates/accept", json=mandate)
        resp = tc.get("/seller/mandates")
    assert resp.status_code == 200
    data = resp.json()
    assert data["count"] == 1
    assert data["mandates"][0]["mandate_id"] == "0xLIST1"


# ── Mode from body test ──────────────────────────────────────────────────────


def test_mode_from_body(mock_client):
    """Mode can be passed in request body (for gateway forwarding)."""
    with TestClient(app) as tc:
        resp = tc.post("/seller/call", json={"mode": "fast"})
    assert resp.status_code == 200
    assert "invoice_id" in resp.json()


# ── Simulation modes ─────────────────────────────────────────────────────────


def test_error_mode(mock_client):
    """Error mode returns 500."""
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=error")
    assert resp.status_code == 500
    assert "Simulated" in resp.json()["error"]


def test_delay_ms_param(mock_client):
    """delay_ms adds extra delay (fast mode, small delay for test)."""
    import time
    start = time.time()
    with TestClient(app) as tc:
        resp = tc.post("/seller/call?mode=fast&delay_ms=50")
    elapsed = time.time() - start
    assert resp.status_code == 200
    # Should take at least ~50ms
    assert elapsed >= 0.04


def test_delay_ms_from_body(mock_client):
    """delay_ms can come from body."""
    with TestClient(app) as tc:
        resp = tc.post("/seller/call", json={"mode": "fast", "delay_ms": 10})
    assert resp.status_code == 200


# ── Seller attestation tests ─────────────────────────────────────────────────


def test_attest_receipt_no_key(mock_client):
    """Attestation fails without SELLER_PRIVATE_KEY."""
    with TestClient(app) as tc:
        resp = tc.post(
            "/seller/receipts/attest",
            json={"receipt_hash": "0x" + "ab" * 32},
        )
    assert resp.status_code == 503
    assert "not configured" in resp.json()["error"]


def test_attest_receipt_missing_hash(mock_client):
    """Attestation fails without receipt_hash."""
    with TestClient(app) as tc:
        resp = tc.post("/seller/receipts/attest", json={})
    assert resp.status_code == 400


@patch.dict("os.environ", {"SELLER_PRIVATE_KEY": "0x" + "5" * 64})
def test_attest_receipt_success(mock_client):
    """Attestation succeeds with valid key and hash."""
    receipt_hash = "0x" + "ab" * 32
    with TestClient(app) as tc:
        resp = tc.post(
            "/seller/receipts/attest",
            json={"receipt_hash": receipt_hash},
        )
    assert resp.status_code == 200
    data = resp.json()
    assert data["receipt_hash"] == receipt_hash
    assert data["signature"].startswith("0x")
    assert data["seller_address"] != ""


@patch.dict("os.environ", {"SELLER_PRIVATE_KEY": "0x" + "5" * 64})
def test_attest_receipt_deterministic(mock_client):
    """Same hash + same key produces same signature."""
    receipt_hash = "0x" + "ab" * 32
    with TestClient(app) as tc:
        resp1 = tc.post("/seller/receipts/attest", json={"receipt_hash": receipt_hash})
        resp2 = tc.post("/seller/receipts/attest", json={"receipt_hash": receipt_hash})
    assert resp1.json()["signature"] == resp2.json()["signature"]
