"""LLM-powered seller service — calls Google Gemini to generate invoice_v1 responses.

Modes:
- fast:    normal Gemini call, returns schema-valid invoice
- slow:    adds artificial delay (~4-6s) before Gemini call
- invalid: corrupts the Gemini response so it fails schema validation

Env vars:
  GEMINI_API_KEY   — required for live Gemini calls
  GEMINI_MODEL     — defaults to gemini-2.0-flash
  SELLER_FALLBACK  — if "true", fall back to deterministic response when Gemini unavailable
  SELLER_ADDRESS   — EVM address of this seller (for capabilities/mandates)

Usage:
    uvicorn seller.main:app --port 8001
"""

from __future__ import annotations

import asyncio
import logging
import os
import time
import uuid

from fastapi import FastAPI, Query, Request
from fastapi.responses import JSONResponse

from seller.gemini_client import GeminiClient, GeminiError
from seller.json_extractor import JSONExtractionError, extract_json

logger = logging.getLogger(__name__)

app = FastAPI(title="SLA-Pay v2 LLM Seller", version="0.3.0")

# ── Mandate store (in-memory) ───────────────────────────────────────────────
_accepted_mandates: dict[str, dict] = {}

# Lazy-initialized client (so tests can replace it)
_gemini_client: GeminiClient | None = None


def get_gemini_client() -> GeminiClient:
    global _gemini_client
    if _gemini_client is None:
        _gemini_client = GeminiClient()
    return _gemini_client


def set_gemini_client(client: GeminiClient | None) -> None:
    """Allow tests to inject a mock client."""
    global _gemini_client
    _gemini_client = client


# ── Prompts ──────────────────────────────────────────────────────────────────

INVOICE_PROMPT = """\
Generate a realistic invoice JSON object with the following exact structure:

{{
  "invoice_id": "<unique string like INV-2026-XXXX>",
  "amount": <positive number — total of line items>,
  "currency": "<one of: USD, EUR, GBP>",
  "line_items": [
    {{
      "description": "<service description>",
      "quantity": <positive integer>,
      "unit_price": <positive number>
    }}
  ],
  "notes": "<optional short note about the invoice>"
}}

Requirements:
- invoice_id must be a non-empty string
- amount must be a non-negative number
- currency must be exactly one of: USD, EUR, GBP
- line_items must have at least 1 item
- each line_item needs description (string), quantity (positive integer), unit_price (non-negative number)
- Make the invoice creative and realistic (different services, amounts each time)
- The amount should equal the sum of (quantity * unit_price) for all line items

Return ONLY the JSON object, no explanation."""

INVALID_PROMPT = """\
Generate a deliberately malformed JSON object that looks like a partial invoice but is missing \
required fields. It should have some invoice-like keys but NOT include all of: \
invoice_id, amount, currency, line_items.

Example of what to produce:
{{"error": "malformed", "partial_data": "incomplete invoice", "status": "failed"}}

Return ONLY the JSON object, no explanation."""


# ── Deterministic fallbacks (when Gemini is unavailable) ─────────────────────

FALLBACK_VALID_INVOICE = {
    "invoice_id": "INV-DEMO-001",
    "amount": 150.00,
    "currency": "USD",
    "line_items": [
        {"description": "AI Query Processing", "quantity": 1, "unit_price": 100.00},
        {"description": "Data Enrichment", "quantity": 2, "unit_price": 25.00},
    ],
    "notes": "Generated by SLA-Pay v2 demo seller (fallback)",
}

FALLBACK_INVALID_RESPONSE = {
    "error": "malformed",
    "partial_data": "incomplete invoice",
}


def _use_fallback() -> bool:
    """Check if we should fall back to deterministic responses."""
    api_key = os.getenv("GEMINI_API_KEY", "")
    fallback = os.getenv("SELLER_FALLBACK", "false").lower() == "true"
    return fallback or not api_key


# ── Endpoints ────────────────────────────────────────────────────────────────


@app.get("/seller/capabilities")
async def capabilities() -> JSONResponse:
    """Expose seller capabilities, supported schemas, and identity."""
    seller_address = os.getenv("SELLER_ADDRESS", "0x0000000000000000000000000000000000000000")
    gemini_model = os.getenv("GEMINI_MODEL", "gemini-2.0-flash")
    has_key = bool(os.getenv("GEMINI_API_KEY", ""))
    return JSONResponse(content={
        "seller_address": seller_address,
        "service": "llm-seller",
        "version": "0.3.0",
        "llm_provider": "google-gemini",
        "llm_model": gemini_model,
        "llm_available": has_key,
        "supported_schemas": ["invoice_v1"],
        "supported_modes": ["fast", "slow", "invalid"],
        "endpoints": {
            "call": "POST /seller/call?mode=fast|slow|invalid",
            "capabilities": "GET /seller/capabilities",
            "mandates_accept": "POST /seller/mandates/accept",
            "health": "GET /seller/health",
        },
    })


@app.post("/seller/mandates/accept")
async def accept_mandate(request: Request) -> JSONResponse:
    """Accept a mandate proposed by the buyer.

    Body: mandate object (must include mandate_id, max_price, validators).
    Seller accepts if the mandate references a supported schema.
    """
    body = await request.json()
    mandate_id = body.get("mandate_id", "")
    if not mandate_id:
        return JSONResponse(status_code=400, content={"error": "mandate_id is required"})

    # Validate that we support the requested validators
    validators = body.get("validators", [])
    supported = {"invoice_v1"}
    for v in validators:
        schema_id = v.get("schema_id", "")
        if schema_id and schema_id not in supported:
            return JSONResponse(
                status_code=400,
                content={"error": f"Unsupported schema: {schema_id}", "accepted": False},
            )

    seller_address = os.getenv("SELLER_ADDRESS", "0x0000000000000000000000000000000000000000")

    _accepted_mandates[mandate_id] = {
        **body,
        "accepted": True,
        "accepted_at": time.time(),
        "seller_address": seller_address,
    }

    logger.info("Mandate accepted: %s (max_price=%s)", mandate_id, body.get("max_price"))

    return JSONResponse(content={
        "mandate_id": mandate_id,
        "accepted": True,
        "seller_address": seller_address,
        "message": "Mandate accepted by seller.",
    })


@app.get("/seller/mandates")
async def list_mandates() -> JSONResponse:
    """List accepted mandates."""
    return JSONResponse(content={
        "mandates": list(_accepted_mandates.values()),
        "count": len(_accepted_mandates),
    })


@app.post("/seller/call")
async def seller_call(request: Request, mode: str = Query(default="fast")) -> JSONResponse:
    """LLM-powered seller endpoint.

    Mode can come from query param or body field. Query param takes precedence.
    Args:
        mode: One of 'fast', 'slow', 'invalid'
    """
    # Also accept mode from body (for gateway forwarding compatibility)
    if mode == "fast":
        try:
            body = await request.json()
            if isinstance(body, dict) and "mode" in body:
                mode = body["mode"]
        except Exception:
            pass

    if mode not in ("fast", "slow", "invalid"):
        return JSONResponse(
            status_code=400,
            content={"error": f"Unknown mode: {mode}. Use fast, slow, or invalid."},
        )

    # Fallback path: deterministic responses when Gemini is unavailable
    if _use_fallback():
        return await _fallback_response(mode)

    # LLM path
    return await _llm_response(mode)


async def _fallback_response(mode: str) -> JSONResponse:
    """Deterministic fallback (same as old demo_seller)."""
    if mode == "fast":
        await asyncio.sleep(0.1)
        return JSONResponse(content=FALLBACK_VALID_INVOICE)
    elif mode == "slow":
        await asyncio.sleep(6.0)
        return JSONResponse(content=FALLBACK_VALID_INVOICE)
    else:  # invalid
        await asyncio.sleep(0.05)
        return JSONResponse(content=FALLBACK_INVALID_RESPONSE)


async def _llm_response(mode: str) -> JSONResponse:
    """Call Gemini and return the result."""
    client = get_gemini_client()

    if mode == "slow":
        # Artificial delay to trigger lower payout tier
        await asyncio.sleep(4.0)

    if mode == "invalid":
        return await _llm_invalid_response(client)

    # fast or slow (after delay): generate valid invoice
    return await _llm_valid_response(client)


async def _llm_valid_response(client: GeminiClient) -> JSONResponse:
    """Generate a schema-valid invoice via Gemini."""
    max_retries = 2
    last_error = ""

    for attempt in range(max_retries + 1):
        try:
            raw = await client.generate(INVOICE_PROMPT, json_mode=True)
            data = extract_json(raw)

            # Quick sanity check for required fields
            if not all(k in data for k in ("invoice_id", "amount", "currency", "line_items")):
                if attempt < max_retries:
                    continue
                # Final attempt failed — return what we got, gateway validator will catch it
                logger.warning("Gemini output missing required fields after retries")

            # Ensure quantity values are integers (LLM sometimes returns floats)
            if "line_items" in data and isinstance(data["line_items"], list):
                for item in data["line_items"]:
                    if "quantity" in item and isinstance(item["quantity"], float):
                        item["quantity"] = int(item["quantity"])

            return JSONResponse(
                content=data,
                headers={"X-LLM-Model": client.model, "X-LLM-Provider": "google-gemini"},
            )

        except (GeminiError, JSONExtractionError) as exc:
            last_error = str(exc)
            logger.warning("Gemini attempt %d failed: %s", attempt + 1, last_error)
            if attempt < max_retries:
                await asyncio.sleep(0.5)

    # All retries exhausted — fall back to deterministic response
    logger.error("Gemini failed after retries: %s — using fallback", last_error)
    return JSONResponse(
        content=FALLBACK_VALID_INVOICE,
        headers={"X-LLM-Model": "fallback", "X-LLM-Provider": "deterministic"},
    )


async def _llm_invalid_response(client: GeminiClient) -> JSONResponse:
    """Generate a deliberately schema-invalid response via Gemini."""
    try:
        raw = await client.generate(INVALID_PROMPT, json_mode=True)
        data = extract_json(raw)
        # Ensure it's actually invalid by removing required fields if present
        for key in ("invoice_id", "amount", "currency", "line_items"):
            data.pop(key, None)
        return JSONResponse(content=data)
    except (GeminiError, JSONExtractionError):
        return JSONResponse(content=FALLBACK_INVALID_RESPONSE)


@app.get("/seller/health")
async def health() -> dict[str, str]:
    has_key = bool(os.getenv("GEMINI_API_KEY", ""))
    return {
        "status": "ok",
        "service": "llm-seller",
        "llm_available": str(has_key).lower(),
    }
