"""Demo seller service — produces deterministic responses for three scenarios.

Modes:
- fast:    valid invoice, immediate response (~100ms)
- slow:    valid invoice, delayed response (~6000ms)
- invalid: malformed JSON (missing required fields)

Usage:
    uvicorn gateway.demo_seller.main:app --port 8001
"""

from __future__ import annotations

import asyncio

from fastapi import FastAPI, Query
from fastapi.responses import JSONResponse

app = FastAPI(title="SLA-Pay v2 Demo Seller", version="0.1.0")

# Deterministic valid invoice response
VALID_INVOICE = {
    "invoice_id": "INV-DEMO-001",
    "amount": 150.00,
    "currency": "USD",
    "line_items": [
        {"description": "AI Query Processing", "quantity": 1, "unit_price": 100.00},
        {"description": "Data Enrichment", "quantity": 2, "unit_price": 25.00},
    ],
    "notes": "Generated by SLA-Pay v2 demo seller",
}

# Invalid response (missing required fields — will fail invoice_v1 schema)
INVALID_RESPONSE = {
    "error": "malformed",
    "partial_data": "incomplete invoice",
}


@app.post("/seller/call")
async def seller_call(mode: str = Query(default="fast")) -> JSONResponse:
    """Demo seller endpoint.

    Args:
        mode: One of 'fast', 'slow', 'invalid'
    """
    if mode == "fast":
        # ~100ms response with valid invoice
        await asyncio.sleep(0.1)
        return JSONResponse(content=VALID_INVOICE)

    elif mode == "slow":
        # ~6s response with valid invoice (triggers base_pay tier)
        await asyncio.sleep(6.0)
        return JSONResponse(content=VALID_INVOICE)

    elif mode == "invalid":
        # Immediate response but schema-invalid
        await asyncio.sleep(0.05)
        return JSONResponse(content=INVALID_RESPONSE)

    else:
        return JSONResponse(
            status_code=400,
            content={"error": f"Unknown mode: {mode}. Use fast, slow, or invalid."},
        )


@app.get("/seller/health")
async def health() -> dict[str, str]:
    return {"status": "ok", "service": "demo-seller"}
